<a href="https://colab.research.google.com/github/mathjihun/Python/blob/pytorch/Tensor_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Numpy**

In [1]:
import numpy as np

###**1D with Numpy**

In [6]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

print("rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

print()
print("t[0] = {}, t[1] = {}, t[-1] = {}".format(t[0], t[1], t[-1]))
print("t[2:5] = {}, t[4:-1] = {}".format(t[2:5], t[4:-1]))
print("t[3:] = {}, t[:5] = {}".format(t[3:], t[:5]))

[0. 1. 2. 3. 4. 5. 6.]
rank of t:  1
Shape of t:  (7,)

t[0] = 0.0, t[1] = 1.0, t[-1] = 6.0
t[2:5] = [2. 3. 4.], t[4:-1] = [4. 5.]
t[3:] = [3. 4. 5. 6.], t[:5] = [0. 1. 2. 3. 4.]


###**2D with Numpy**

In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print()

print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


###**Pytorch with Tensor**

In [9]:
import torch

###**1D with PyTorch**

In [12]:
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(t)
print()

print(t.dim())
print(t.shape)
print(t.size())

print()
print(t[0], t[1], t[-1])  
print(t[2:5], t[4:-1])    
print(t[:2], t[3:])       

tensor([0., 1., 2., 3., 4., 5., 6.])

1
torch.Size([7])
torch.Size([7])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


###**2D with PyTorch**

In [16]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)
print()

print(t.dim())  
print(t.size()) 

print(t[:, 1:])
print(t[1:3, 1:2])    #기존 python 배열에서는 안 되던 부분

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

2
torch.Size([4, 3])
tensor([[ 2.,  3.],
        [ 5.,  6.],
        [ 8.,  9.],
        [11., 12.]])
tensor([[5.],
        [8.]])


###**Broadcasting**