###**Numpy**

In [1]:
import numpy as np

###**1D with Numpy**

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

print("rank of t: ", t.ndim)
print("Shape of t: ", t.shape)

print()
print("t[0] = {}, t[1] = {}, t[-1] = {}".format(t[0], t[1], t[-1]))
print("t[2:5] = {}, t[4:-1] = {}".format(t[2:5], t[4:-1]))
print("t[3:] = {}, t[:5] = {}".format(t[3:], t[:5]))

[0. 1. 2. 3. 4. 5. 6.]
rank of t:  1
Shape of t:  (7,)

t[0] = 0.0, t[1] = 1.0, t[-1] = 6.0
t[2:5] = [2. 3. 4.], t[4:-1] = [4. 5.]
t[3:] = [3. 4. 5. 6.], t[:5] = [0. 1. 2. 3. 4.]


###**2D with Numpy**

In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print()

print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank  of t:  2
Shape of t:  (4, 3)


###**Numpy 여러가지 기능**

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print()

print(np.append(A, [4, 5]))   #한 줄로 펴주면서 뒤에 붙임

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6 4 5]


In [21]:
z = np.zeros((3, 4))    #기본 dtype은 flaot이다.
o = np.ones((2, 3))
f = np.full((2, 3), 4)    #2행 3열을 4로 채우자.
e = np.empty((3, 3))    #그냥 쓰레기값이 들어있는 3행 3열의 배열을 달라는 것
i = np.eye(3)

In [22]:
a = [[1, 2, 3], [4, 5, 6]]
z = np.zeros_like(a)    #a와 같은 구조를 갖되 그것을 다 0으로 채워서 달라는 의미
o = np.ones_like(a)
e = np.empty_like(a)
f = np.full_like(a, 2)

In [24]:
k = np.arange(10)
k2 = np.arange(24).reshape(-1, 6)
ud = np.random.rand(2, 3)    #uniform distribution
gd = np.random.randn(2, 2)    #Gaussian distribution

print(k)
print(k2)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [28]:
c = np.arange(16).reshape(-1, 4)

bool_idx = (c > 10)
print(bool_idx)
print()
print(c[bool_idx])

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]]

[11 12 13 14 15]


In [41]:
c = np.arange(8)
d = np.arange(1, 9).reshape(8, -1)
print(d)
print()

v = np.vstack((c, c, c, c))     #vertical 즉 수직으로 쌓는 것이기에 세로로 쌓인다.
print(v)
print()

h = np.hstack((d, d, d, d))    #horizontal 즉 수평으로 쌓는 것이기에 가로로 쌓인다.
print(h)
print()

t = np.arange(16).reshape(2, 2, 4)
print(t.transpose(2, 1, 0))    # t[x][y][z] -> t[z][y][x]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]]

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [46]:
a = np.arange(24).reshape(4, -1)
b = a.copy()     # a를 완전히 동일하게 복사하지만 서로 저장된 주소가 다르기 때문에 b를 고쳐도 a가 바뀌지 않는다. 둘이 동일하게 바뀌게 하고 싶으면 .view()를 이용

c = np.concatenate((a, b), axis=-1)   # 이건 사실상 hstack((a, b))과 차이 x
print(c, c.shape)
print()

c2 = np.concatenate((a, b), axis=0)   # 이건 사실상 vstack((a, b))과 차이 x
print(c2, c2.shape)
print()

d = np.stack((a, b), axis=1)    #얘는 새로운 차원을 하나 만들어서 갖다 붙인다.
print(d, d.shape)       #4x6이 4x2x6이 됨

e = np.expand_dims(a, axis=0)    #4x6을 1x4x6으로 바꿈
print(e, e.shape)

[[ 0  1  2  3  4  5  0  1  2  3  4  5]
 [ 6  7  8  9 10 11  6  7  8  9 10 11]
 [12 13 14 15 16 17 12 13 14 15 16 17]
 [18 19 20 21 22 23 18 19 20 21 22 23]] (4, 12)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (8, 6)

[[[ 0  1  2  3  4  5]
  [ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [18 19 20 21 22 23]]] (4, 2, 6)
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [38]:
e = np.arange(32).reshape(8, 4)

print(e)
print()

print(e[[1, 5, 7, 2]])     # index 1, 5, 7, 2인 행을 가져와서 쌓아준다.
print()

print(e[[1, 5, 7, 2], [0, 3, 1, 2]])     # index가 (1, 0), (5, 3), (7, 1), (2, 2)인 요소들로 새롭게 array를 만든다.

print()

print(e[[1, 5, 7, 2]][:, [0, 3, 1, 2]])     # 이 경우는 e[[1, 5, 7, 2]]에다가 [:, [0, 3, 1, 2]]가 붙은 것이므로 e[[1, 5, 7, 2]]가 열 위치만 바꾸게 된다.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

[ 4 23 29 10]

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [ ]:
z = np.arange(1, 25).reshape(2, 3, 4)
print(z)
print()

print(np.sum(z))
print()

print(np.sum(z, axis=0))    #즉 3, 4가 된다     z[0, :, :] + z[1, :, :]
print(np.sum(z, axis=1))    #즉 2, 4가 된다.    z[:, 0, :] + z[:, 1, :] + z[:, 2, :]
print(np.sum(z, axis=2))    #즉 2, 3이 된다.    z[:, :, 0] + z[:, :, 1] + z[:, :, 2] + z[:, :, 3]

# 다만 이 부분은 torch에서 하는 게 더 좋아 보인다. 딱히 차이는 없다. 좀 더 간결해진다.

###**Pytorch with Tensor**

In [50]:
import torch

###**1D with PyTorch**

In [ ]:
t = torch.FloatTensor([0, 1, 2, 3, 4, 5, 6])
print(t)
print()

print(t.dim())
print(t.shape)
print(t.size())

print()
print(t[0], t[1], t[-1])  
print(t[2:5], t[4:-1])    
print(t[:2], t[3:])       

tensor([0., 1., 2., 3., 4., 5., 6.])

1
torch.Size([7])
torch.Size([7])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


###**2D with PyTorch**

In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)
print()

print(t.dim())  
print(t.size()) 

print(t[:, 1:])
print(t[1:3, 1:2])    #기존 python 배열에서는 안 되던 부분

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

2
torch.Size([4, 3])
tensor([[ 2.,  3.],
        [ 5.,  6.],
        [ 8.,  9.],
        [11., 12.]])
tensor([[5.],
        [8.]])


###**Broadcasting**

broadcasting의 규칙

1. 배열의 랭크가 같지 않으면 두 모양이 같은 길이가 될 때까지 배열의 낮은 랭크 쪽에 1을 붙입니다.

2. 두 배열은 차원에서 크기가 같거나 배열 중 하나의 차원에 크기가 1인 경우 차원에서 호환 가능하다고 합니다.

3. 배열은 모든 차원에서 호환되면 함께 broadcast 될 수 있습니다.

4. broadcast 후 각 배열은 두 개의 입력 배열의 요소 모양 최대 개수와 동일한 모양을 가진 것처럼 동작합니다.

5. 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫 번째 배열은 마치 해당 차원을 따라 복사된 것처럼 작동합니다.

실제로 동작하는 방식

1. A와 B의 모양을 생각합니다.

2. 두 배열이 len(A.shape) == len(B.shape)인지 확인을 합니다.

3. 같지 않은 경우에는 두 배열의 모양 길이가 같아질때까지 적은 쪽의 shape 앞에 1을 추가해줍니다.
ex) (5, 3) -> (1, 5, 3)

4. shape이 1인 곳은 복사가 됩니다.
ex) (5, 3) + (3, ) 
 -> (5, 3) + (1, 3) 
 -> (5, 3) + (5, 3)

 추가적으로 예를 들어 (1, 2)와 (1, 3)은 연산이 불가능하다.
 왜냐하면 일단 차원이 같다.
 다음으로 1=1 ok 다음으로
 2 != 3 -> 둘중 하나가 1인가? No 따라서 불가능

In [100]:
a = np.arange(9).reshape(3, 3)
b = np.full_like(a, 2)

print(a*b)    # elementwise multiplication
print(a@b)    # matrix multiplication

t = torch.from_numpy(a*b)    # numpy => torch

t = t.type(torch.float64)    # type()을 통하여서 data type을 바꿀 수 있다.
# 다만 t.float() 이렇게 해도 바꿀 수 있다.

t_mean = t.mean()
t_mean0 = t.mean(dim=0)     # 평균을 구할 수 있다. t[0, :], t[1, :], t[2, :]의 평균
t_mean1 = t.mean(dim=1)     # 평균을 구할 수 있다. t[:, 0], t[:, 1], t[:, 2]의 평균

print(t_mean, t_mean0, t_mean1)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 6  6  6]
 [24 24 24]
 [42 42 42]]
tensor(8., dtype=torch.float64) tensor([ 6.,  8., 10.], dtype=torch.float64) tensor([ 2.,  8., 14.], dtype=torch.float64)


In [66]:
z = torch.arange(1, 25).reshape(2, 3, 4)
print(z)
print()

print(z.sum())
print()

print(z.sum(dim=0))    #즉 3, 4가 된다     z[0, :, :] + z[1, :, :]
print(z.sum(dim=1))    #즉 2, 4가 된다.    z[:, 0, :] + z[:, 1, :] + z[:, 2, :]
print(z.sum(dim=2))    #즉 2, 3이 된다.    z[:, :, 0] + z[:, :, 1] + z[:, :, 2] + z[:, :, 3]

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

tensor(300)

tensor([[14, 16, 18, 20],
        [22, 24, 26, 28],
        [30, 32, 34, 36]])
tensor([[15, 18, 21, 24],
        [51, 54, 57, 60]])
tensor([[10, 26, 42],
        [58, 74, 90]])


In [70]:
t = torch.FloatTensor([[1, 2], [3, 4]])

print(t.max())
print(t.max(dim=0))
print()

print(t.max(dim=0)[0])
print(t.max(dim=0)[1])   # t.argmax(dim=0)

# 물론 min도 전부 동일하게 적용된다.

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

tensor([3., 4.])
tensor([1, 1])


tensor([1, 1])

In [73]:
t = torch.arange(24).reshape(2, 2, 6)
x = t.view(-1, 3)    # view와 reshape의 차이는? view는 원본 즉 여기서는 t와 x의 data를 공유하고 싶다면 사용합니다. 메모리도 절약 가능

print(t)
print(x)

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]])


In [84]:
t = torch.arange(24).reshape(2, 2, 6)
x = t.view(4, 1, 2, 1, -1)

print(x.shape)

y = x.squeeze()

print(y.shape) # 1인 차원을 모두 제거합니다.

z = y.unsqueeze(dim=0)

print(z.shape)

torch.Size([4, 1, 2, 1, 3])
torch.Size([4, 2, 3])
torch.Size([1, 4, 2, 3])


In [98]:
x = torch.arange(4).view(-1, 2).float()
y = torch.arange(5, 9).view(-1, 2).float()

z1 = torch.cat([x, y], dim=0)   # numpy에서는 concatenate였지만 여기선 그냥 cat
z2 = torch.cat([x, y], dim=1)   # 하나의 덩어리로서 쌓고 싶을 때 사용

print(z1)
print(z2)

print()
print(torch.stack([x, y]))       # 따로따로 구분해서 즉 데이터 추가 느낌으로 쌓고 싶을 때 사용
print(torch.stack([x, y], dim=0))    # 첫번째 차원 방향으로 쌓는다.
print(torch.stack([x, y], dim=1))    # 두번째 차원 방향으로 쌓는다.

tensor([[0., 1.],
        [2., 3.],
        [5., 6.],
        [7., 8.]])
tensor([[0., 1., 5., 6.],
        [2., 3., 7., 8.]])

tensor([[[0., 1.],
         [2., 3.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[0., 1.],
         [2., 3.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[0., 1.],
         [5., 6.]],

        [[2., 3.],
         [7., 8.]]])
